version: '3'

services:
  drill-admin:
    image: drill4j/admin:${ADMIN_VERSION}
    container_name: drill-admin
    environment:
      - TEST2CODE_PLUGIN_VERSION=${TEST2CODE_PLUGIN_VERSION}
      - JAVA_TOOL_OPTIONS="-Dplugin.feature.drealtime=true"
      - LOG_LEVEL=trace
      - DRILL_DEFAULT_PACKAGES=org/springframework/samples/petclinic
      - DRILL_DB_HOST=${POSTGRES_HOST}
      - DRILL_DB_PORT=5432
      - DRILL_DB_NAME=${POSTGRES_DB}
      - DRILL_DB_USER_NAME=${POSTGRES_USER}
      - DRILL_DB_PASSWORD=${POSTGRES_PASSWORD}
      - analytic.disable=true
    ports:
      - 9090:8090
      - 6006:5006
    depends_on:
      postgres:
        condition: service_started
    networks:
      - drill4j-dev-network

  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - drill4j-dev-network

  admin-ui:
    image: drill4j/admin-ui-root-config:${ADMIN_UI_ROOT_CONFIG_VERSION}
    container_name: admin-ui
    environment:
      - UI_PLUGINS_URLS=test2code#https://cdn.jsdelivr.net/npm/@drill4j/test2code-ui@${TEST2CODE_UI_VERSION}/dist/Drill4J-test-to-code.js
    ports:
      - 9091:8080
    depends_on:
      drill-admin:
        condition: service_started
    networks:
      - drill4j-dev-network

  browser-proxy:
    container_name: browser-proxy
    image: drill4j/browser-proxy:0.2.0
    ports:
      - 7777:7777
    networks:
      - drill4j-dev-network

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4445:4444"
    networks:
      - drill4j-dev-network
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "drill4j-dev-network"]


  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    ports:
      - "7070:8080"
    networks:
      - drill4j-dev-network
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  chrome:
    image: selenoid/chrome:96.0
    container_name: chrome

  firefox:
    image: selenoid/firefox:94.0
    container_name: firefox

networks:
  drill4j-dev-network:
    external: false
    name: drill4j-dev-network
