version: '3'

services:
  spring-petclinic-sample:
    image: drill4j/spring-petclinic-sample:${PET_STANDALONE_BUILD}
    container_name: spring-petclinic-sample
    ports:
      - ${PET_STANDALONE_PORT}:8080
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=${adminAddress},agentId=${agentId},buildVersion=${PET_STANDALONE_BUILD},logLevel=${LOG_LEVEL}"
    volumes:
      - ./distr:/data
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
