version: '3'

services:
  drill-admin:
    image: drill4j/admin:${BACK_VERSION}
    container_name: drill-admin
    environment:
      - TEST2CODE_PLUGIN_VERSION=${TEST2CODE_PLUGIN_VERSION}
      - TEST2CODE_PLUGIN_URL=${TEST2CODE_PLUGIN_URL}
      - JAVA_TOOL_OPTIONS="-Dplugin.feature.drealtime=true"
      - LOG_LEVEL=trace
      - DRILL_DEFAULT_PACKAGES=org/springframework/samples/petclinic
    ports:
      - 9090:8090
      - 6006:5006
    networks:
      - drill4j-dev-network

  admin-ui:
    image: drill4j/admin-ui-root-config:${FRONT_VERSION}
    container_name: admin-ui
    environment:
      - UI_PLUGINS_URLS=${UI_PLUGINS_URLS}
    ports:
      - 9091:8080
    networks:
      - drill4j-dev-network

  browser-proxy:
    container_name: browser-proxy
    image: drill4j/browser-proxy:0.2.0
    ports:
      - 7777:7777
    networks:
      - drill4j-dev-network

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4445:4444"
    networks:
      - drill4j-dev-network
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "drill4j-dev-network"]


  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    ports:
      - "8083:8080"
    networks:
      - drill4j-dev-network
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  chrome:
    image: selenoid/chrome:96.0
    container_name: chrome

  firefox:
    image: selenoid/firefox:94.0
    container_name: firefox

networks:
  drill4j-dev-network:
    external: false
    name: drill4j-dev-network
