version: '3'

services:
  start-petclinic-microservice-tests:
    image: drill4j/petclinic-microservice-autotests-execute:0.1.3
    container_name: start-petclinic-microservice-tests
    environment:
      - petclinicUrl=http://api-gateway:8080
      - adminHost=host.docker.internal
      - adminPort=9090
      - groupId=dev-pet-mcr
      - autotestAgentVersion=${AUTOTEST_AGENT_VERSION}
      - agentRunnerVersion=${AGENT_RUNNER_VERSION}
networks:
  drill4j-dev-network:
    external: true
