version: '3'

services:
  todo-mvc:
    image: drill4j/todomvc-typescript-angular:${BUILD} # 1.0.0
    container_name: todo-mvc
    environment:
      - JS_PARSER_VERSION=${JS_PARSER_VERSION}
      - JS_AGENT_HOST=js-agent
      - JS_AGENT_PORT=8080
      - SERVE_FILES_ON_PORT=${TODO_MVC_PORT}
    ports:
      - 6072:6072
    networks:
      - drill4j-dev-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  drill4j-dev-network:
    external: true
