version: '3'

services:
  start-petclinic-tests:
    image: ${AUTOTESTS_IMAGE}   # drill4j/petclinic-autotests-execute:0.3.2
    container_name: start-petclinic-tests
    environment:
      - petclinicUrl=http://spring-petclinic-sample:8080
      - adminHost=drill-admin
      - adminPort=8090
      - agentId=dev-pet-standalone
      - autotestAgentVersion=${AUTOTEST_AGENT_VERSION}
      - agentRunnerVersion=${AGENT_RUNNER_VERSION}
      - params=${AUTOTESTS_PARAMS} # :testng:test -DtestNGVersion=7.4.0 -Dtestng.dtd.http=true
      - withProxy=${WITH_PROXY}
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
    external: true
