version: '3'

services:
  start-petclinic-tests:
    image: drill4j/petclinic-autotests-execute:0.2.0
    container_name: start-petclinic-tests
    environment:
      - petclinicUrl=http://host.docker.internal:8087
      - adminHost=host.docker.internal
      - adminPort=9090
      - agentId=dev-pet-standalone
      - autotestAgentVersion=0.17.7
    networks:
      - drill4j-dev-network
    depends_on:
      - selenoid

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4445:4444"
    networks:
      - drill4j-dev-network
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "drill4j-dev-network"]


  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    ports:
      - "8083:8080"
    networks:
      - drill4j-dev-network
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

networks:
  drill4j-dev-network:
    external: true
    # external:
    #   name: drill4j-dev-network # This assumes network is already created

#  chmod ugo+rwx /selenium/selenium-server-standalone-3.13.0.jar
#  DISPLAY=:1 xvfb-run java -jar selenium-server-standalone-3.13.0.jar
#  chmod +rwx selenium-server-standalone-3.141.59.jar

#   selenoid:
#     image: "aerokube/selenoid:latest"
#     container_name: selenoid
#     ports:
#       - "4445:4444"
#     networks:
#       - drill4j-dev-network
#     volumes:
#       - ".:/etc/selenoid"
#       - "./target:/output"
# #      - "/var/run/docker.sock:/var/run/docker.sock" # for linux
#       - "//var/run/docker.sock:/var/run/docker.sock" # for windows
#       - "./target:/opt/selenoid/video"
#     environment:
#       - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
#     command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "drill4j-dev-network" ]

#   selenoid-ui:
#     image: "aerokube/selenoid-ui:latest"
#     container_name: selenoid-ui
#     links:
#       - selenoid
#     ports:
#       - "8083:8080"
#     networks:
#       - drill4j-dev-network
#     command: [ "--selenoid-uri", "http://selenoid:4444" ]