version: '3'

services:
  agent-files:
    image: drill4j/java-agent:${JAVA_AGENT_VERSION}
    environment:
      - AGENT_VERSION=${JAVA_AGENT_VERSION}
    volumes:
      - agent-files:/data
    networks:
      - drill4j-dev-network

  spring-petclinic-sample:
    image: drill4j/spring-petclinic-sample:${PET_STANDALONE_BUILD}
    container_name: spring-petclinic-sample
    ports:
      - ${PET_STANDALONE_PORT}:8080
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/agent/libdrill_agent.so=drillInstallationDir=/data/agent,adminAddress=${ADMIN_ADDRESS},agentId=dev-pet-standalone,buildVersion=${PET_STANDALONE_BUILD},logLevel=${LOG_LEVEL}"
    volumes:
      - agent-files:/data
    networks:
      - drill4j-dev-network
    depends_on:
      agent-files:
        condition: service_completed_successfully


volumes:
  agent-files:

networks:
  drill4j-dev-network:
    external: true
