version: '3'

services:
  start-petclinic-tests:
    image: drill4j/petclinic-autotests-execute:0.3.0
    container_name: start-petclinic-tests
    environment:
      - petclinicUrl=http://spring-petclinic-sample:8080
      - adminHost=drill-admin
      - adminPort=8090
      - agentId=dev-pet-standalone
      - autotestAgentVersion=${AUTOTEST_AGENT_VERSION}
      - runner=${RUNNER}
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
    external: true
