version: '3'

services:
  start-petclinic-tests:
    image: antonpatsev/petclinic-autotests-feature-selenoid:5
    container_name: start-petclinic-tests
    environment:
      - petclinicUrl=http://host.docker.internal:8087
      - adminHost=host.docker.internal
      - adminPort=9090
      - agentId=dev-pet-standalone
      - autotestAgentVersion=${AUTOTEST_AGENT_VERSION}
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
    external: true
