version: '3'

services:
  single-js-agent-tests:
    container_name: single-js-agent-tests
    image: drill4j/example-js-selenium-mocha:1.0.0
    environment:
      APP_URL: http://host.docker.internal:${TODO_MVC_PORT}
      SELENIUM_HUB_HOST: host.docker.internal
      SELENIUM_HUB_PORT: 4444

      DRILL4J_ADMIN_BACKEND_URL: http://${ADMIN_ADDRESS}
      DRILL4J_DEVTOOLS_PROXY_URL: http://host.docker.internal:8093
      DRILL4J_AGENT_ID: todomvc-typescript-angular

      DEBUG: 'drill:*'
      DEBUG_COLORS: 'true'
      FORCE_COLOR: '3'
      DEBUG_LOG_LEVEL: '4'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
    external: true
