name: Run Tests

on:
  repository_dispatch:
    types: [ run_test_for_component ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.admin_version }}"'
      - run: 'echo "client_payload: ${{ toJson(github.event.client_payload) }}"'

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install

      - name: Run tests
        id: run_tests
        uses: "./.github/manual-run-tests-for-component"
        with:
          access_token: '${{ secrets.VEE_TABLE_TOKEN }}'
# Generate Personal Github token with workflow scopes.
# Run action
# curl -H "Authorization: token xxx" \
#    -H 'Accept: application/vnd.github.everest-preview+json' \
#    "https://api.github.com/repos/Drill4J/e2e/dispatches" \
#    -d '{ "event_type": "run_test", "client_payload": {"admin_version": "1.0.58"}}'
