name: Run Repository_Dispatch

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.admin_version }}"'
      - run: 'echo "client_payload: ${{ toJson(github.event.client_payload) }}"'
