name: Run Workflow Dispatch

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'admin-ui-root-config version'     
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: |
        echo "admin-ui-root-config version: ${{ github.event.inputs.version }}"
